### ISSUE TITLE
Internal server error when new user tries to use the extension

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/spotify-slack-status#4]
I see this error in the Heroku logs:

```
2017-10-24T22:45:02.680809+00:00 app[web.1]: I, [2017-10-24T22:45:02.680735 #4]  INFO -- : GET https://api.spotify.com/v1/me/player/currently-playing
2017-10-24T22:45:02.819021+00:00 app[web.1]: 2017-10-24 22:45:02 - TypeError - no implicit conversion of nil into String:
2017-10-24T22:45:02.819023+00:00 app[web.1]: 	/app/vendor/ruby-2.3.4/lib/ruby/2.3.0/json/common.rb:156:in `initialize'
2017-10-24T22:45:02.819024+00:00 app[web.1]: 	/app/vendor/ruby-2.3.4/lib/ruby/2.3.0/json/common.rb:156:in `new'
2017-10-24T22:45:02.819025+00:00 app[web.1]: 	/app/vendor/ruby-2.3.4/lib/ruby/2.3.0/json/common.rb:156:in `parse'
2017-10-24T22:45:02.819026+00:00 app[web.1]: 	/app/models/fetcher.rb:30:in `get'
2017-10-24T22:45:02.819027+00:00 app[web.1]: 	/app/models/spotify_api.rb:17:in `get_currently_playing'
2017-10-24T22:45:02.819027+00:00 app[web.1]: 	/app/app.rb:188:in `block in <top (required)>'
```

Slackbot showed this to the user:

```
*/spotify-status * failed with the error "500_service_error"
```

/cc @shortsparty

**Comment by cheshire137** [comment]
Shorts tells me he wasn't listening to any music at the time. I'll have the app respond with "no music playing" instead of a 500 error.
